#### The Logit Model

In [ ]:
# Import numpy library for numerical calculations
import numpy as np

In [ ]:
# Define the number of zones and destinations
n_zones = 4
n_dests = 3

In [ ]:
# Define the population and household data for each zone
pop = np.array([1000, 800, 600, 400]) # Population
hh = np.array([200, 150, 120, 80]) # Households

# Define the number of trips to each destination for each zone
trips = np.array([[50, 30, 20],
                  [40, 25, 15],
                  [30, 20, 10],
                  [20, 15, 5]])

# Define the distance, cost and time data for each pair of zone and destination
dist = np.array([[10, 15, 20],
                 [12, 18, 24],
                 [14, 21, 28],
                 [16, 24, 32]]) # Distance in km
cost = np.array([[5, 7.5, 10],
                 [6, 9, 12],
                 [7, 10.5, 14],
                 [8, 12, 16]]) # Cost in $
time = np.array([[20, 30, 40],
                 [24, 36, 48],
                 [28, 42, 56],
                 [32, 48, 64]]) # Time in minutes

In [ ]:
# Define the mode choice data for each pair of zone and destination
mode = np.array([["Car", "Bus", "Train"],
                 ["Car", "Bus", "Train"],
                 ["Car", "Bus", "Train"],
                 ["Car", "Bus", "Train"]]) # Mode of transport

In [ ]:
# Define the coefficients for distance, cost and time
beta_dist = -0.1 # Coefficient for distance
beta_cost = -0.2 # Coefficient for cost
beta_time = -0.3 # Coefficient for time

In [ ]:
# Calculate the total cost for each pair of zone and destination
total_cost = beta_dist * dist + beta_cost * cost + beta_time * time

# Calculate the probability of choosing each destination for each zone
prob = np.exp(-total_cost) / np.sum(np.exp(-total_cost), axis=1, keepdims=True)

In [ ]:
# Print the results
print("The probability matrix is:")
print(prob)

The probability matrix is:
[[3.29320439e-04 1.79802867e-02 9.81690393e-01]
 [6.71713836e-05 8.16202286e-03 9.91770806e-01]
 [1.36236314e-05 3.68418971e-03 9.96302187e-01]
 [2.75618540e-06 1.65879651e-03 9.98338447e-01]]
